[project]
name = "core"
version = "0.1.0"
description = "Core functionality"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "msgpack>=1.1.0",
    "numpy>=2.2.1",
    "pydantic>=2.10.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
